controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
data_source:
    path: /data-source
    controller: App\Controller\DataController::dataSource
    methods: POST